[project]
name = "opsparser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "matplotlib>=3.10.1",
    "openseespy>=3.7.1.2",
    "pytest>=8.3.5",
]
